name: Build Static Site
on: [push]
jobs:
  build-static-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: cp -r cms/posts/* src/routes/posts/
      - run: npm run build
      - name: deploy 
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
